-- CreateEnum
CREATE TYPE "SCHEDULINGS_STATUS" AS ENUM ('RUNNING', 'PENDING', 'FAILED', 'STOPPED');

-- AlterTable
ALTER TABLE "schedulings" ADD COLUMN     "status" "SCHEDULINGS_STATUS" NOT NULL DEFAULT 'PENDING';
