-- CreateTable
CREATE TABLE "cars" (
    "id" SERIAL NOT NULL,
    "brand" TEXT,
    "name" TEXT,
    "bodyType" TEXT,
    "painting" TEXT,
    "carType" TEXT,
    "driveType" TEXT,
    "transmissionType" TEXT,
    "color" TEXT,
    "mileage" INTEGER,
    "engine" TEXT,
    "engineDisplacement" INTEGER,
    "fuelType" TEXT,
    "safety" JSONB,
    "interior" JSONB,
    "electronics" JSONB,
    "owners" TEXT,
    "status" TEXT,
    "year" INTEGER,
    "inspected" TEXT,
    "plate" TEXT,
    "additionalInformation" TEXT,
    "others" TEXT,
    "roadWorthy" TEXT,
    "price" DOUBLE PRECISION,
    "images" TEXT[],
    "phone" TEXT,
    "seller" TEXT,
    "link" TEXT,

    CONSTRAINT "cars_pkey" PRIMARY KEY ("id")
);
