import type { CAR_BODY_TYPE } from '../enums/CarBodyType';
import type { CAR_BRAND } from '../enums/CarBrand';
import type { CAR_COLOR } from '../enums/CarColor';
import type { CAR_FUELTYPE } from '../enums/CarFuelType';
import type { CAR_PAINTING_TYPE } from '../enums/CarPaintingType';
import type { CAR_TRANSMISSION_TYPE } from '../enums/CarTransmissionType';
import type { IBaseInterface } from './base/IBaseInterface';
import type { ICarElectronicsInterface } from './ICarElectronicsInterface';
import type { ICarInteriorInterface } from './ICarInteriorInterface';
import type { ICarSafetyInterface } from './ICarSafetyInterface';
import type { ICarSpecificationsInterface } from './ICarSpecificationsInterface';

export interface ICarInterface extends IBaseInterface {
  brand: CAR_BRAND;
  name: string;
  bodyType: CAR_BODY_TYPE;
  painting: CAR_PAINTING_TYPE;
  carType: CAR_TYPE;
  driveType: string;
  transmissionType: CAR_TRANSMISSION_TYPE;
  color: CAR_COLOR;
  mileage: number;
  engine: string;
  engineDisplacement: number;
  fuelType: CAR_FUELTYPE;
  safety: ICarSafetyInterface;
  interior: ICarInteriorInterface;
  specifications: ICarSpecificationsInterface;
  electronics: ICarElectronicsInterface;
  owners: string;
  status: string;
  year: number;
  inspected: string;
  plate: string;
  additionalInformation: string;
  others: string;
  roadWorthy: string;
  price: number;
  images: string[];
  phone: string;
  seller: string;
  link: string;
}
