import Sidebar from '@/components/layout/sidebar';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'IA',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex min-h-screen bg-gray-100">
      <Sidebar />
      {children}
    </div>
  );
}
